events {}

http {
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_prefer_server_ciphers on;
    resolver 8.8.8.8;
    merge_slashes on;
    server_tokens off;

    proxy_set_header   Host $host;
    proxy_set_header   X-Real-IP $remote_addr;
    proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
    gzip on;
    gzip_comp_level 4;

    map $http_upgrade $connection_upgrade {
        default Upgrade;
        '' close;
    }

    ### domain certificate check ###
    server {
        listen 80;
        server_name cannon.programbus.ru www.cannon.programbus.ru andrew.programbus.ru www.andrew.programbus.ru;

        location /check {
            add_header Content-Type text/plain;
            return 200 'alive-cert\n';
        }

        location ^~ /.well-known/acme-challenge/ {
            alias /var/www/dehydrated/;
            try_files $uri =404;
        }    

        location / {
            return 301 https://$host$request_uri;
        }
    }
}
