resolver 8.8.8.8;

server {
    listen 80;
    server_name cannon.programbus.ru www.cannon.programbus.ru;
    server_tokens off;

	location /check {
		add_header Content-Type text/plain;
		return 200 'alive\n';
	}
	
    location ^~ /.well-known/acme-challenge/ {
        alias /var/www/dehydrated/;
        try_files $uri =404;
    } 
}